spring:
  datasource:
    dynamic:
      primary: zhiyi-cloud-mall-v1_1
      strict: true
      tenant:
        prefix: zhiyi-cloud-mall-v1_
        enable: true
      datasource:
        zhiyi-cloud-mall-v1_1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
          url: jdbc:mysql://127.0.0.1:3306/zhiyi-cloud-mall-v1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        zhiyi-cloud-mall-v1_2:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
          url: jdbc:mysql://127.0.0.1:3306/zhiyi-cloud-mall-v1_1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      table-underline: true
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler

security:
  oauth2:
    resource:
      id: mall-v1-api-admin

logging:
  level:
    root: INFO
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG
    com.github.taoroot: DEBUG
