server:
  port: 8008

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
      x-forwarded:
        enabled: true
        host-enabled: true
      discovery:
        locator:
          enabled: false # 不要自动支持,手动配置
          lower-case-service-id: true
          filters:
            - PreserveHostHeader
            - StripPrefix=1
      routes:
        - id: upms
          uri: lb://flizi-auth
          predicates:
            - Path=/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka-server:8848/eureka/
