server:
  port: 6222

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka-server:8848/eureka/

spring:
  application:
    name: admin
  security:
    user:
      name: admin
      password: password
